version: 1.1.2.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /p:ApplicationVersion={%APPVEYOR_BUILD_VERSION%}
artifacts:
- path: $(APPVEYOR_PROJECT_NAME)\bin\Debug\app.publish\*
  name: published