version: 1.1.2.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: $psw = ConvertTo-SecureString -String $env:pfx_password -AsPlainText -Force
  - ps: $root = $env:APPVEYOR_BUILD_FOLDER
  - ps: Import-PfxCertificate -FilePath $root'\Symlink Creator\cert.pfx' -CertStoreLocation cert:\CurrentUser\My -Password $psw  
build_script:
- ps: msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /p:ApplicationVersion="$env:APPVEYOR_BUILD_VERSION" /p:Configuration=Release /p:Platform="Any CPU"
after_build:
- ps: $root = Resolve-Path '.\Symlink Creator\bin\Release\app.publish'; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }

