# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "amd989"
repo = "Symlinker"

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
## What's Changed

{%- if version %} in {{ version | trim_start_matches(pat="v") }}{%- endif -%}
{% for commit in commits %}
  {% if commit.remote.pr_title -%}
    {%- set commit_message = commit.remote.pr_title -%}
  {%- else -%}
    {%- set commit_message = commit.message -%}
  {%- endif -%}
  * {{ commit_message | split(pat="\n") | first | trim }}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
    {% if commit.remote.pr_number %} in \
      [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
    {%- endif %}
{%- endfor -%}

{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  {% raw %}\n{% endraw -%}
  ### New Contributors
{%- endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif -%}

{% if version %}
    {% if previous.version %}
      **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
    {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
---

## Legacy Versions

The following versions were released before the project moved to GitHub and used a different versioning system.

### Version 1.1.1.10 - 2013-08-31

- Uploaded to GitHub (migrated from Google Code)
- Added ClickOnce check for updates support - automatic updates on app launch (work in progress)
- Minor changes

### Version 1.1.1.3 - 2010-10-30

- **Fixed** Minor bug fixes
- **Modified** GUI redesign to support foreign Windows OS
- Minor code revisions
- **TODO** Add UAC support
- **TODO** Manage errors from mklink (currently succeeds even if link wasn't created)

### Version 1.1.0.6 - 2010-07-26

- **Fixed** Minor bug fixes
- **Added** Back the functionality to choose network locations (was disabled for unknown reason)

### Version 1.1.0.5 - 2010-03-20

- **Fixed** Error changing the type of symbolic link from file to folder
- **Added** Tooltips with information

### Version 1.1.0.3 - 2010-02-06

- **Fixed** Display name - now shows app name instead of "Microsoft" as publisher

### Version 1.1.0.0 - 2010-02-03

- **Added** Functionality to create file symbolic links (previously only folder symlinks)
  - Thanks to jasoneg for the suggestion

### Version 1.0.0.8 - 2009-08-16

- **Fixed** Minor bug when creating links in a folder that already has a folder with the same name
- **Added** Better looking icon for Windows 7 users (installable version only)

---
<!-- generated by git-cliff -->
"""
# An array of regex based postprocessors to modify the changelog.
# Replace the placeholder `<REPO>` with a URL.
postprocessors = []

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = false
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"
# Parse and group commits based on patterns
commit_parsers = [
    # Conventional commits
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^docs", group = "Documentation" },
    { message = "^ci", group = "Build & CI" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^chore", group = "Other Changes" },
    { message = "^build", group = "Build & CI" },

    # Pattern matching for non-conventional commits
    { message = "^[Aa]dd(ed|ing)?", group = "Features" },
    { message = "^[Ff]ix(ed|ing)?", group = "Bug Fixes" },
    { message = "^[Uu]pdat(e|ed|ing)", group = "Other Changes" },
    { message = "^[Ee]nabl(e|ed|ing)", group = "Features" },
    { message = "^[Dd]isabl(e|ed|ing)", group = "Other Changes" },
    { message = "^[Rr]emov(e|ed|ing)", group = "Other Changes" },
    { message = "^[Cc]hang(e|ed|ing)", group = "Other Changes" },
    { message = "^[Mm]ov(e|ed|ing)", group = "Refactoring" },
    { message = "^[Rr]earrang(e|ed|ing)", group = "Refactoring" },
    { message = "^[Tt]ry(ing)?", group = "Other Changes" },

    # Skip noise commits
    { message = "^[Mm]erge", skip = true },
    { message = "^[Ss]aving SLN", skip = true },
    { message = "^[Uu]pload(ed)?\\s+(\\d+\\.)+\\d+", skip = true },
    { message = "^[Uu]pdate support$", skip = true },
    { message = "^[Uu]pdate README", skip = true },
    { message = "^[Uu]pdating appveyor", skip = true },
    { message = "^[Uu]pdated Changelog", skip = true },
    { message = "^[Aa]dding space", skip = true },
    { message = "^[Dd]elete README", skip = true },
    { message = "^[Cc]reate README", skip = true },
    { message = "^[Mm]oved Readme", skip = true },
    { message = "^[Cc]hanging appveyor", skip = true },
]